"""Step 5: export model outputs as site/data.js for the static results site.

The site is fully self-contained (file:// friendly): data is embedded as a
JS constant instead of fetched, so no server or CORS setup is needed.
Re-run this script after every new simulation to refresh the site.
"""
import json, sys
from datetime import date
sys.path.insert(0, "src")
import pandas as pd
from wc26.elo import ratings_asof

tbl = pd.read_csv("outputs/tournament_probs_v1.csv", index_col=0)
elo = ratings_asof(pd.read_parquet("outputs/elo_history.parquet"), "2026-06-11")

teams = []
for t, r in tbl.iterrows():
    teams.append({
        "team": t, "group": r["group"], "elo": round(float(elo[t])),
        **{c: float(r[c]) for c in ["P1", "P2", "P3", "P4", "P_qualify", "P_R32",
                                    "P_R16", "P_QF", "P_SF", "P_final", "P_champion",
                                    "P_top_scoring_team"]},
    })

data = {
    "generated": str(date.today()),
    "n_sims": 20000,
    "seed": 26,
    "model_version": "v1 (Elo-driven Dixon-Coles, official bracket, calibrated shootouts)",
    "backtest": {
        "tournament": "World Cup 2022 (64 matches, point-in-time fit)",
        "log_loss_model": 1.062, "log_loss_uniform": 1.099,
        "calib_predicted": 0.544, "calib_observed": 0.562,
    },
    "dc_params": {"beta_home": 0.111, "beta_away": -0.234, "beta_elo": 0.719,
                  "xi": 0.0018, "n_matches": 20477},
    "shootout": {"b_home": 0.309, "b_elo": 0.677, "n": 677,
                 "ll_model": -462.5, "ll_coin": -469.3},
    # External benchmarks recorded 2026-06-11 (tournament eve) — do not overwrite.
    "betmgm_outright": {"Spain": 450, "France": 500, "England": 700, "Brazil": 800,
                        "Portugal": 900, "Argentina": 900, "Germany": 1400,
                        "Netherlands": 2000, "United States": 5000},
    "kalshi_usa_group": 0.51,
    "klement": "Netherlands champions (final vs Portugal); England and Spain out in the semis",
    "teams": teams,
}

with open("site/data.js", "w") as f:
    f.write("// Generated by scripts/05_export_site_data.py — do not edit by hand.\n")
    f.write("const WC26 = " + json.dumps(data, indent=1) + ";\n")
print(f"site/data.js written: {len(teams)} teams")
